### ISSUE TITLE
BookRating

### ISSUE THREAD

**Issue by CBernsCode** [IvyLeVay/Blue-Team#3]
There should be two separate ratings for each metric in user and always positive. This way if a user prefers fiction i.e. -5.0 on the users fictNonFict rating. They will only effect the fiction rating in book.
These metrics can be ordered in an 2d array but need to be positive. 

Users are this or that, Books have thisRating and thatRating

**Comment by cnellis101** [comment]
I kept the 2D array but removed the negative numbers. Please let me know if that resolves the issue.

**Comment by CBernsCode** [comment]
The changes do not addess the issue.
Each rating -5.0 to 5.0 in users has two only positive ratings in book. One for fiction and one for non fiction. If we are going to store them in an array we must make a way to access it properly based on what rating we are modifying. 
I keep saying it.
Each SINGLE rating in User has TWO ratings in books.
